### ISSUE TITLE
Example programs should be extracted to their own repo

### ISSUE THREAD

**Issue by virtuald** [wpilibsuite/EclipsePlugins#102]
It's highly annoying to try and find the examples. Make it a repo, and then during the plugin build process it pulls down the examples.

Reference: https://www.chiefdelphi.com/forums/showthread.php?t=155024, but I'm sure that's not the only person who has been confused.

**Comment by 333fred** [comment]
Not sure if I'm a fan. I certainly understand the desire to have things split out, but it's *another* dependency that needs to be pulled, another set of jobs, and so on.

To be clear, I'm not against improving access to the examples. I'm just worried that we already have too many repos.

**Comment by virtuald** [comment]
My opinion is that access to the examples should be prioritized.

**Comment by JLLeitschuh** [comment]
Gradle has composite builds which makes it easier to test artifacts created in other projects(or git repos) together.
https://docs.gradle.org/current/userguide/composite_builds.html

**Comment by PeterJohnson** [comment]
Done in #142.
