### ISSUE TITLE
Ultrasonic C++ example doesn't compile

### ISSUE THREAD

**Issue by PeterMitrano** [wpilibsuite/EclipsePlugins#119]
the last line is erroneous, and should be removed. then it is correct

**Comment by JLLeitschuh** [comment]
Shouldn't the samples get compiled as part of some test to make sure this sort of thing doesn't happen?

**Comment by PeterMitrano** [comment]
Agree, but apparently they don't...

**Comment by AustinShalit** [comment]
Duplicate of #106

Take a look at https://github.com/wpilibsuite/allwpilib/pull/569 for the java version.
The C++ version was started in https://github.com/wpilibsuite/allwpilib/commit/9c804c13519dc94e82c6a4dc275153d8149190d0

**Comment by PeterJohnson** [comment]
Should be fixed thanks to #142.
