### ISSUE TITLE
Javadocs should be sourced from DocumentationBuilder

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/EclipsePlugins#131]

**Comment by ThadHouse** [comment]
I'll work on this. It would actually need to grab the docs from the individual repos, not DocumentationBuilder. DocumentationBuilder only builds the HTML website.

**Comment by ThadHouse** [comment]
Actually, digging into this more, it might be worth it to have DocumentationBuilder generate a javadoc jar as well. This would enable proper links, which is better.

**Comment by ThadHouse** [comment]
Closed by #132
