### ISSUE TITLE
Setting HOME messes up expected directories

### ISSUE THREAD

**Issue by 333fred** [wpilibsuite/EclipsePlugins#15]
When you set the HOME env variable (I do this on Windows so I can put my dotfiles where I want them), the plugins unzips the wpilib folder to user home, not where I set it to. Then, actually building a program expects the wpilib folder to be in where I've set HOME to, not the user home. So I have two directories:
- `C:\Users\333fr\wpilib` - Where the wpilib folder is unzipped to.
- `C:\otherdir\wpilib` - Where the eventual build expects to find the wpilib folder.

**Comment by Kevin-OConnor** [comment]
I assume the desired behavior here is to respect the env variable for the install?

**Comment by PeterJohnson** [comment]
Yes, I think so.

**Comment by 333fred** [comment]
Yeah. Ideally, I should also be able to set an env variable like WPILIB_INSTALL_DIR or something of the like that and have it install there.

**Comment by JLLeitschuh** [comment]
Isn't this why I added vagrant?
Does this work there?
Or would this be a build artifact has this problem?

**Comment by 333fred** [comment]
This has nothing to do with vagrant. This an issue with the plugins, not the build.

**Comment by Kevin-OConnor** [comment]
The problem is the Eclipse plugins installing the wpilib files on users machine. I don't think vagrant helps there.

Somewhere we must be using different variables to figure out where to install vs where to look for the files when building. I think it will be easy to find and fix, but I want to get the 3rd party stuff done before I look at it.

-------- Original message --------

**Comment by Kevin-OConnor** [comment]
I think doing both "WPILIB_DIR" or whatever, and respecting HOME and using user.home if neither are there starts to get a bit messy. If you had to pick between "WPILIB_DIR" and "HOME", with "HOME" being the easier to implement, what are your thoughts?

**Comment by 333fred** [comment]
`WPILIB_DIR`, without a doubt. The only reason I have `HOME` set is so that I can easily share my dotfiles among my Windows computers, and it doesn't really break anything on Windows. It'll break a lot on anything 'Nix based.

**Comment by Kevin-OConnor** [comment]
Ok, I'll try to figure out the one issue left to do that one then.

-------- Original message --------

**Comment by Kevin-OConnor** [comment]
So, after doing some work on this one, allowing a different install location opens up a can of worms that I am not convinced is worth it. 

Specifically, it complicates installer creation for 3rd party installers, requires these installers to be re-run if the var is created or changed after they are installed and requires a DS change to be able to auto-launch the SmartDashboard from multiple possible locations.

Considering all of that, I think the appropriate fix here is to always install to user.home and fix what is currently causing breakage in Fred's scenario of HOME being set on Windows.

**Comment by 333fred** [comment]
Ok. If we fix that, it'll at least make builds work on my machine without having to mess with settings.

**Comment by Kevin-OConnor** [comment]
I have this working for new Eclipse installs (or existing if you delete the Eclipse variable for WPILIB in Window->Preferences->Run/Debug->String Substitution and restart Eclipse after starting the plugins). Is that good enough or do you want me to work on adding something to reset this for existing installs?

**Comment by 333fred** [comment]
Confirmed working on my machine. Thanks Kevin.
