### ISSUE TITLE
Allow adding resource files to the robot jar

### ISSUE THREAD

**Issue by AarjavP** [wpilibsuite/EclipsePlugins#174]
Resource files are incredibly useful for easy configuration, especially for logging frameworks.

This can be achieved by simply removing the `include="**/*.java"` restriction when creating the jar at https://github.com/wpilibsuite/EclipsePlugins/blob/master/edu.wpi.first.wpilib.plugins.java/src/main/resources/java-zip/ant/build.xml#L118

Another option might be to only include `properties`, `xml`, `json`, and `yaml` files or specify resources directory in `build.properties`. I believe eclipse automatically treats the src dir as resource root so using that as the default might be okay.

**Comment by sciencewhiz** [comment]
Also requested here: https://www.chiefdelphi.com/forums/showthread.php?threadid=161422
