### ISSUE TITLE
Add support for using shared HAL and ntcore

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/EclipsePlugins#34]
In order to improve 3rd party library support, we should switch the HAL and ntcore to be linked to shared instead of statically. The necessary changes have already been PR'd to allwpilib (https://github.com/wpilibsuite/allwpilib/pull/291) and ntcore (https://github.com/wpilibsuite/ntcore/pull/139). The changes we need in eclipse are as followed.

C++:
- copy `libHALAthena.so` and `libntcore.so` from the c++ build libraries to the rio (probably `/usr/local/frc/lib`

Java:
- During plugin build, when we get the latest maven artifact, it should include a `nativelibraries.jar` file. We need the 2 files from that `libwpilibJavaJNI.so` and `libHALAthena.so` moved to a directory where it can be copied to the robot.
- During plugin build, get libntcore.so either from ntcore maven, or potentially from the C++ artifact, and move that into a directory it can be copied from.
- During deploy, make sure all 3 libraries `libwpilibJavaJNI.so`, `libHALAthena.so` and `libntcore.so` get moved to the robot, most likely in `/usr/local/frc/lib`.

When doing this, we most likely want #27 as well.

**Comment by Kevin-OConnor** [comment]
Fixed in #38
