### ISSUE TITLE
C++ deploy should deploy stripped binary

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/EclipsePlugins#4]
Currently, built C++ binaries include debug information, resulting in a very large executable.  Since we're using remote debugging, the deployed binary doesn't need to contain the debug information (only the local one used by the debugger for symbols).  Stripping the deployed binary would significantly reduce its size, speeding up uploads and reducing flash wear on the target.

**Comment by ThadHouse** [comment]
This was fixed a while ago. Closing
