### ISSUE TITLE
Merge WPILibC and WPILibJ native dependencies

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/EclipsePlugins#48]
Right now, we have 2 copies of `libntcore.so`, `libHALAthena.so`, and `libwpiutil.so` in the plugins, one for C++ and 1 for Java. We might want to combine these into one folder location, potentially in `core` so we don't have multiple copies of the same libraries, along with multiple copies of the debug objects

**Comment by 333fred** [comment]
I'm not convinced this is actually an issue for anyone but us. Do we think teams install both Java and C++, or just the one they need?

**Comment by PeterJohnson** [comment]
It's not uncommon.  We actually recommend people install the C++ version of Eclipse even if they're using Java, after all... but disk space is cheap, so I don't have a lot of heartburn about two copies.  The other issue is if both plugins install stuff to the same location, I'm not sure how well that will work, and I'd hate to add a 3rd plugin just for this.

**Comment by ThadHouse** [comment]
I was thinking adding the common libraries to the core part of the template, however that's a good point about them potentially interfering with each other. If a team somehow installed one version of java and another version of C++ we could run into issues. So maybe this isn't a good idea or necessary.

**Comment by Kevin-OConnor** [comment]
@ThadHouse It's not possible to install different versions of CPP and Java in the same Eclipse as they both depend on Core so you will have a dependency conflict if you try to just update one of them.

**Comment by ThadHouse** [comment]
Yeah thinking about this more its not necessary. Disk space is fairly cheep anyway and they're not that big to begin with.
