### ISSUE TITLE
Eclipse plugins always deploy Debug binary

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/EclipsePlugins#5]
During testing, 3512 noticed that our roboRIO wasn't running the latest version of our code. We determined this was due to the Eclipse C++ plugins always deploying the Debug binary. When the build configuration is set to Release, the Release binary is not deployed as expected.

**Comment by Kevin-OConnor** [comment]
WPILib created projects don't have a Release configuration...

**Comment by calcmogul** [comment]
I did a clean install of the plugins in a VM and made a new project. It seems that a project I created with an older version of the plugins has a Release configuration, but new ones do not.
