### ISSUE TITLE
Remove CANTalon from examples

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/EclipsePlugins#75]
In C++ and Java examples
- [x] Ultrasonic Example
- [x] CANTalon example
- [x] CANTalonPID example
- [x] GyroMecanum

**Comment by bradamiller** [comment]
In addition the following examples need to be updated to the new camera server.

- [ ] AxisCameraSample
- [ ] 2015Vision
- [ ] IntermediateVision
- [ ] QuickVision

**Comment by sciencewhiz** [comment]
A few more that use CANTalon

- [ ] UltrasonicPID
- [ ] Gyro
