### ISSUE TITLE
Deploy and use netconsole-host

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/EclipsePlugins#80]
Netconsole-host was removed from the image, but is still quite useful for debugging (namely, riolog doesn't work without it).  We should distribute the binary with the plugins and deploy it along with the shared libraries.

**Comment by sciencewhiz** [comment]
I can resurrect the 2015 code for deploying and using netconsole-host. Back then, I think the executable was included as a resource (and not built and published). Any objections to just including the executable?
