### ISSUE TITLE
Deleted java user libraries not handled well

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/EclipsePlugins#89]
If a user adds a java library to the user libraries directory and then deletes it (after the project autoupdater runs), the deleted library isn't deleted from the .classpath. This causes all java projects to be marked with an issue in eclipse because of the missing items in the classpath.

This does not affect building, but is annoying.

**Comment by Kevin-OConnor** [comment]
Yeah, I noticed this when we were adding the third party stuff, but wasn't sure we want remove everything that's not in that folder from the classpath. Though I guess we do something similar in C++
