### ISSUE TITLE
User entered libraries are removed from project configuration

### ISSUE THREAD

**Issue by rp-first** [wpilibsuite/EclipsePlugins#92]
If I manually add a library to my project configuration, then restart eclipse, my library is no longer in the configuration. My list of libraries returns to wpi and whatever is in the wpilib/user/cpp/lib folder -- nothing else. During the season, my team builds three unique robots and several bits of test hardware. Common code is placed in team developed libraries and is updated regularly. The robot projects then include those libraries in their configuration. If I manually edit the project configuration, my changes should not be undone by the wpilibsuite plugin.

There is a work-around in that I can create empty files in the wpilib/user/cpp/lib folder that represent the team libraries, then manage the library paths to make sure the actual libraries are found before the empty placeholder. This does not seem like a good solution.

 Also, the list of libraries in the eclipse configuration is always sorted alphabetically which causes dependency problems. That is, if I move my libraries to the wpilib/user/cpp/lib folder (or create the placeholders in that folder) there are still problems because they get linked in the wrong order.

At this time the only solutions I have is to edit the properties of each project every time eclipse is opened and/or rename the libraries so their alphabetical order matches the dependency order.

**Comment by sciencewhiz** [comment]
How are you adding the libraries to the project?

**Comment by rp-first** [comment]
In Eclipse, right click on the project, select properties, under the C/C++ General ->Paths and Symbols, there is a Libraries tab. Click on the Add button and enter the library name. Also need to add something in the Library Path tab so Eclipse knows how to find your library. **This is what is not working**.

For now we are creating empty libraries under c:/Users/<user>/wpilib/cpp/lib. To add libraries Team1, gsi, and gsu we are adding **empty** files aibTeam1.a, bibgsu.a, and cibgsi.a - -we change the first letter from 'l' to something else. This is to force the libraries to link in the correct order. The WPI plugin apparently uses the full filename to sort the list of libraries, then it discards the first three chars which would normally be "lib". Note that you still need to update the LibraryPath, and you want to make sure the path to your actual libraries (soemthing like: "$(ProjDirPath)/../gsi/$(ConfigName)" ) is listed first. This is all just to get around what I would consider a bug with the plug-ins. 

To create the libraries, we do File -> New -> Other ... -> Robot C++ Project, Next, give it a name, Finish. This makes sure we get the correct Toolchain and other important settings. Then, under that projects properties -> C/C++ Build -> Settings -> Build Artifacts, we change the Artifact type to a Static Library, set the name (like gsi), set the extension to "a" and the prefix to "lib". Then we delete all files associated with the original project and add our source files.

**Comment by Kevin-OConnor** [comment]
If, instead of wiping out all libraries and only adding back ones from wpilib/user/cpp/lib we check and remove any libraries that don't exist on the library paths (whether they were added manually or automatically by being placed in wpilib/user/cpp/lib) would that work for you?

I am trying to avoid maintaining a list of libraries we have added automatically because the only safe place to store that list is in the project directory (if you delete your /wpilib folder the library reference will still be in your project) and I would prefer not to put a file there if we can help it. But we do need some way of making sure we are removing libraries that were automatically added if they get deleted from user/cpp/lib.

**Comment by rp-first** [comment]
In my opinion, the best option would be for the software to say if there is a library in wpilib/user/ccp/lib, make sure it is in the list of libraries -- add it, if it's not already there. I don't think the software should ever have to remove items from the list. It would be rare for anyone to remove a library from a project and if they did they know what they are doing well enough to remove it from the configuration too. So, I'm not seeing the reason for removing all of the libraries from the list, I suspect there is a good reason that I'm just not seeing.

Your suggestion of not removing items from the list if they are found in the path is an OK solution once I have an initial build. If I clone three projects (a robot project and two libraries), and add them to eclipse, it is my understanding that the libraries would be removed from the apps list of libraries before I had a chance to build them. So, I would need to manage things by importing the libraries, building them, then importing the robot project. I'm not sure what would happen if I do a clean all, then build.

I think the biggest problem associated with rebuilding the list, or even adding items to the list is maintaining the dependency order -- with the current scheme it's just lucky that wpi is so late in the alphabet because it is the thing that the other libraries depend on.

Maybe under the WPI preferences there could be a checkbox that says something about managing the libraries manually/automatically. Have it default to automatic (what it does now) but let me change it so I can manage them myself if desired.

**Comment by rp-first** [comment]
This change seems to work well for our use. Thank you.
